# Generated by Django 2.1.7 on 2019-03-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20170307_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_code', models.CharField(max_length=8)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('active', models.BooleanField(default=True)),
                ('house', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=185)),
                ('dist', models.CharField(max_length=185)),
                ('state', models.CharField(max_length=185)),
            ],
        ),
    ]
