# Generated by Django 2.1.7 on 2019-03-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_userinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
    ]
