# Generated by Django 2.1.7 on 2019-03-17 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0008_remove_userinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ms_code_updater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intcode', models.PositiveIntegerField(default=1112)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ms_code',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(default=111111, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
