# Generated by Django 2.1.7 on 2019-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20190318_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ms_code_updater',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='college',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='college_reg_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='dept',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='food_pref',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mob_no',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
