# Generated by Django 2.1.7 on 2019-09-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_auto_20190902_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='food_pref',
            field=models.CharField(blank=True, default='ND', max_length=10),
        ),
    ]
