# Generated by Django 2.1.7 on 2019-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_auto_20190903_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='payment_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='college',
            field=models.CharField(blank=True, default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='college_reg_id',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dept',
            field=models.CharField(blank=True, default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mob_no',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
