# Generated by Django 2.1.7 on 2019-09-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_auto_20190904_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='mc',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='meme',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='opm',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='tiktok',
        ),
    ]
