# Generated by Django 2.1.7 on 2019-09-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0017_auto_20190904_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_no_log', models.CharField(default=None, max_length=10)),
                ('email_log', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
