# Generated by Django 2.1.7 on 2019-09-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0018_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='cs',
            field=models.BooleanField(default=False),
        ),
    ]
