# Generated by Django 2.1.7 on 2019-09-05 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0019_userprofileinfo_cs'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='refuser',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='logprofile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
