# Generated by Django 2.2.1 on 2019-09-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0021_auto_20190905_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='Year',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
