# Generated by Django 2.2.1 on 2019-09-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0023_auto_20190906_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mob_no',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
